---
apiVersion: v1
kind: Namespace
metadata:
  name: app-test-01
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-test-01
    env: staging
  name: app-test-01
  namespace: app-test-01
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-test-01
  template:
    metadata:
      labels:
        app: app-test-01
    spec:
      containers:
      - image: nginx:latest
        name: nginx
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-test-01
    app.kubernetes.io/instance: app-test-01
    env: staging
  name: app-test-svc
  namespace: app-test-01
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app-test-01
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-localhost
  namespace: app-test-01
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: app-test-01
            port:
              number: 31688
        path: /
        pathType: Prefix
